apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce-gtid-consistency=ON
    binlog_expire_logs_seconds=86400  # Keep binlogs for 1 day
    binlog_do_db=test
    skip-name-resolve
    default-authentication-plugin=mysql_native_password

  slave.cnf: |
    [mysqld]
    server-id=2
    relay-log=relay-bin
    read_only=1
    gtid_mode=ON
    enforce-gtid-consistency=ON
    skip-name-resolve
    default-authentication-plugin=mysql_native_password
    replicate_do_db=test
