apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    binlog_do_db=test
    enforce-gtid-consistency=ON
    gtid-mode=ON
    sync_binlog=1
    innodb_flush_log_at_trx_commit=1
    log-slave-updates=ON
    skip-name-resolve
    default-authentication-plugin=mysql_native_password

  slave.cnf: |
    [mysqld]
    server-id=2
    relay-log=relay-bin
    read_only=1
    enforce-gtid-consistency=ON
    gtid-mode=ON
    skip-name-resolve
    default-authentication-plugin=mysql_native_password
