apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-restart-detector
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: mysql-resync-script
                defaultMode: 0744
            restartPolicy: OnFailure
          containers:
            - name: restart-detector
              image: bitnami/kubectl:latest
              command: ["/bin/sh", "-c", "/scripts/detect-restart.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
