apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-restart-detector
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            fsGroup: 2000
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: mysql-resync-script
          containers:
            - name: restart-detector
              image: bitnami/kubectl:latest
              command: ["/bin/sh", "-c"]
              args: 
                - |
                  chmod +x /tmp/detect-restart.sh
                  /tmp/detect-restart.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /tmp
