apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-restart-detector
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: mysql-resync-script
            - name: etc-hosts
              emptyDir: {}
          containers:
            - name: restart-detector
              image: bitnami/kubectl:latest
              securityContext:
                readOnlyRootFilesystem: false
              command: ["/bin/sh", "-c"]
              args: 
                - |
                  chmod +x /detect-restart.sh
                  /detect-restart.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /
                - name: etc-hosts
                  mountPath: /etc/hosts
