---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:latest
          command: ["sh", "-c", "
            until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -D $MYSQL_DATABASE -e 'SELECT 1'; do
              echo 'Waiting for MySQL...';
              sleep 5;
            done;
            mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -D $MYSQL_DATABASE -e '
              CREATE DATABASE IF NOT EXISTS test;
              use test;
              CREATE TABLE IF NOT EXISTS data (
                id INT AUTO_INCREMENT PRIMARY KEY,
                value DOUBLE NOT NULL
              );
            ';
          "]
          env:
            - name: MYSQL_HOST
              #value: "mysql-0.mysql.default.svc.cluster.local"
              value: "mysql-slave-0.mysql-slave.default.svc.cluster.local"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "test"
      containers:
        - name: reader
          image: docker.io/muk007/reader:version-20
          ports:
            - containerPort: 5000
            - containerPort: 8001
          env:
            - name: MYSQL_HOST
              #value: "mysql-1.mysql.default.svc.cluster.local"
              value: "mysql-slave-0.mysql-slave.default.svc.cluster.local"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: reader-service
  labels:
    app: reader
spec:
  selector:
    app: reader
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
