apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader
        image: docker.io/muk007/reader:version-1
        ports:
        - containerPort: 5000
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: reader-service
  labels:
    app: reader-service
spec:
  selector:
    app: reader
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
