apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: writer-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: writer-service
  endpoints:
    - port: http
      interval: 5s
      path: /metrics
