apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: writer
        image: docker.io/muk007/writer:version-3
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: "mysql-0.mysql.default.svc.cluster.local"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: writer-service
spec:
  selector:
    app: writer
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 
