---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:latest
          command: ["sh", "-c", "
            until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -D $MYSQL_DATABASE -e 'SELECT 1'; do
              echo 'Waiting for MySQL...';
              sleep 5;
            done;
            mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -D $MYSQL_DATABASE -e '
              CREATE TABLE IF NOT EXISTS data (
                id INT AUTO_INCREMENT PRIMARY KEY,
                value DOUBLE NOT NULL
              );
            ';
          "]
          env:
            - name: MYSQL_HOST
              #value: "mysql-0.mysql.default.svc.cluster.local"
              value: "mysql-master-0.mysql-master.default.svc.cluster.local"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "test"
      containers:
        - name: writer
          image: docker.io/muk007/writer:version-20
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              #value: "mysql-0.mysql.default.svc.cluster.local"
              value: "mysql-master-0.mysql-master.default.svc.cluster.local"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: writer-service
  labels:
    app: writer
spec:
  selector:
    app: writer
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
