name: Apply Infra (Runs post "Validate Infra")

on:
  workflow_run:
    workflows: ["Validate Infra"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  wait-for-approval:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment: dev # Approval is needed for dev env.

    steps:
      - name: Awaiting manual approval
        run: echo "Approval granted, proceeding to apply..."

  apply-changes:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      #- name: Configure AWS creds
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
      #    aws-region: us-west-2
   
      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Apply changes
        run: |
          terraform -chdir=terraform init
          terraform -chdir=terraform apply -auto-approve

      - name: Wait
        run: sleep 300

      - name: Apply Manifests
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=minikube-server" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --parameters '{
              "commands": [
                "export KUBECONFIG=/home/ubuntu/.kube/config",
                "cd /home/ubuntu",
                "rm -rf dyninno-project", 
                "git clone https://github.com/devops-contribution/dyninno-project.git",
                "sudo snap install helm --classic",
                "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts",
                "helm repo update",
                "helm install prometheus prometheus-community/kube-prometheus-stack",
                "kubectl apply -f ./dyninno-project/manifests/."
              ]
            }' \
            --comment "Apply Kubernetes manifests"
    
      - name: Implement Istio (Testing)
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=minikube-server" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --parameters '{
              "commands": [
                "export KUBECONFIG=/home/ubuntu/.kube/config",
                "cd /home/ubuntu",
                "rm -rf dyninno-project", 
                "git clone https://github.com/devops-contribution/dyninno-project.git",
                "sudo snap install helm --classic",
                "sudo helm repo add istio https://istio-release.storage.googleapis.com/charts",
                "sudo helm repo update",
                "sudo helm install istio-base istio/base -n istio-system --create-namespace --kubeconfig ~/.kube/config",
                "sudo helm install istiod istio/istiod -n istio-system --kubeconfig ~/.kube/config",
                "sudo helm install istio-ingress istio/gateway -n istio-system --kubeconfig ~/.kube/config",
                "kubectl apply -f dyninno-project/misc/.",
                "kubectl label namespace test istio-injection=enabled"
              ]
            }' \
            --comment "Implement Istio"
