name: Build and Deploy

on:
  workflow_dispatch:
  
  push:
    branches: ["main"]
    paths:
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.TAG }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Tag Number
        id: set_tag
        run: |
          VERSION="version-${{ github.run_number }}"
          echo "TAG=$VERSION" >> $GITHUB_ENV
          echo "TAG=$VERSION" >> $GITHUB_OUTPUT  # Save output

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with Context (reader)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: devops/reader.Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/reader:${{ env.TAG }}"

      - name: Build Docker Image with Context (writer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: devops/writer.Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/writer:${{ env.TAG }}"

  # We are just updating the image tag using a PR, this isn't an actual deployment.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Transform version for TAG
        run: echo "TAG=$(echo '${{ needs.build.outputs.image_tag }}"' | tr ' ' '-')" >> $GITHUB_ENV
        
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Update Version in File
        run: |
          yq -i ".spec.template.spec.containers[0].image = \"docker.io/muk007/${{ TAG }}\"" manifests/reader.yaml
          yq -i ".spec.template.spec.containers[0].image = \"docker.io/muk007/${{ TAG }}\"" manifests/writer.yaml


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          branch: "feature/${TAG}"
          base: "main"
          title: "Bump to ${TAG}"
          body: "Bump to ${TAG}"
          labels: automated
