name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.TAG }}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Tag Number
        id: set_tag
        run: |
          VERSION="version-${{ github.run_number }}"
          echo "TAG=$VERSION" >> $GITHUB_ENV
          echo "TAG=$VERSION" >> $GITHUB_OUTPUT  # Save output

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with Context
        uses: docker/build-push-action@v6
        with:
          context: .
          file: devops/reader.Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/reader:${{ env.TAG }}"
