name: Python Linting

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Change as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint app/reader/reader.py
          pylint app/writer/writer.py
