name: Validate Infra

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-validate-plan:
    name: Validate & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # Either use role or access keys to authenticate AWS, both approaches are shown below.
  
      #- name: Configure AWS creds
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
      #    aws-region: us-west-2

      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # This secret is being passed from repo secrets in github.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # This secret is being passed from repo secrets in github.
          aws-region: us-west-2

      - name: Validate & Plan
        run: |
          terraform -chdir=terraform init
          terraform -chdir=terraform validate
          terraform -chdir=terraform plan
